services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    hostname: mongo1
    volumes:
      - G:/node-mongodb-local-server/mongodb-backups:/backups
      - mongo1-data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - mongo-replica-net

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    hostname: mongo2
    volumes:
      - mongo2-data:/data/db
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - mongo-replica-net

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    hostname: mongo3
    volumes:
      - mongo3-data:/data/db
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - mongo-replica-net

networks:
  mongo-replica-net:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
